ksw/implementation of descriptions and examples in the preference schema json
CARTAvis/CARTAvis.github.io pull request #6
Opened 2021-03-17 06:25 UTC by kswang1029

This PR is to address https://github.com/CARTAvis/carta-frontend/issues/1339 and includes
1. a description per keyword
2. an example or enum when needed
3. revision of some input validation policies (correct me if the revision is not sensible)
4. add validation policy for color hex code.

Some descriptions contain ???, meaning I don't quite understand what the keyword means. Please advice.

@acdo2002 @YuHsuan-Hwang please help to check the descriptions and examples from a user point of view if you have time.

2021-03-17 06:30 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "description": "???"
best to just leave this description out. It's used by carta-controller

2021-03-17 06:30 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "description": "Set the color theme of the graphical user interface of CARTA. Options are 'auto' (refering to OS theme if applicable), 'light', and 'dark'.",
do we need the options listed if we already have an enum?

2021-03-17 06:31 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "type": "boolean",
if the default is true, we should probably put this in the schema as well using the `default` property

2021-03-17 06:32 UTC, kswang1029 commented on schemas/preference_schema_1.json
> +            "description": "Set the color theme of the graphical user interface of CARTA. Options are 'auto' (refering to OS theme if applicable), 'light', and 'dark'.",
I suggest we do. enum helps users to select one easily but if users want to revise what has been selected, the description helps I think.

2021-03-17 06:35 UTC, kswang1029 commented on schemas/preference_schema_1.json
> +            "description": "???"
ok

2021-03-17 06:38 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "description": "Set the image smoothing mode before computing contour vertices. An integer should be provided. Options are: {0: 'None', 1: 'Block', 2: 'Gaussian' (as default)}. Use 'conto
this is an example where we should switch to a string enum, I reckon. But that would be a breaking change, so we should combine it with other changes

2021-03-17 06:39 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "description": "Set the default region type of the region creation button in the image viewer. An integer should be given. Options are: {0: 'Point', 1: 'Line' (NOT IMPLEMENTED YET), 2: 'P
we should make another enum string migration here

2021-03-17 06:41 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "enum": [
this shouldn't be an enum, because it can be any value. It should rather be a list of examples

2021-03-17 06:43 UTC, kswang1029 commented on schemas/preference_schema_1.json
> +            "enum": [
uh true🙈 corrected

2021-03-17 10:38 UTC, kswang1029 commented
To generate an html manual, try (thanks to @veggiesaurus ):

> \# Install using "pip install json-schema-for-humans"
generate-schema-doc --minify --no-link-to-reused-ref --expand-buttons ../config/config_schema.json ../docs/config_schema.html

2021-03-17 10:57 UTC, kswang1029 commented
@veggiesaurus descriptions are revised and should be more concise now in the html manual. please re-review.

2021-03-18 09:21 UTC, acdo2002 commented
I checked `CARTAvis.github.io/schemas/preference_schema_1.json` description and found the corresponding function in the CARTA/File/Preference. 
At least for me, most of them are easy to understand what each function means.

(1) I do not know "fileSortingString" & "fileFilteringType"? which CARTA/File/Preference/Global function they correspond to?
(2) scaling description: allow integer 0-5, but scaling maximun: 7 , please check whether it is correct?
(3) Typo: Preference/Global/"Tranparent" (should be ''Transparent" right?) image background, I suppose this is a typo frontend issue?

2021-03-19 01:51 UTC, kswang1029 commented
@acdo2002 thanks for checking.
1) they are "implicit" preferences that need to be remembered by the frontend but there is no need to have them in the preferences menu.
2) that part will be fixed in other PR and will be changed to human-readable enum strings.
3) which part is it?

2021-03-19 02:11 UTC, acdo2002 commented
I see.
About (3) typo is on the carta frontend -> click "File" and click "Preference" menu bar -> check "Global". 
On the bottom, the last line shows
![Tranparent Image Background](https://user-images.githubusercontent.com/34430648/111721452-e0099e80-889a-11eb-8f28-a2c0cd3e7a58.png)
I suppose it should be Tran"s"parent Image Background? (now the screen shows "Tranparent" Image Background)

2021-03-19 02:17 UTC, kswang1029 commented
uh ok. I will fix it. 👍

2021-03-23 07:47 UTC, YuHsuan-Hwang commented
I have read through the descriptions. Just found some ranges of the parameters different from UI, such as scalingGamma: [0, 2] and scalingAlpha: no limit. Do the ranges have to be consistent?

2021-03-23 07:51 UTC, kswang1029 commented
@YuHsuan-Hwang thanks for checking. Regarding your concerns, I suggest they should be consistent (that can be done in other PR along with two other human-readable enum changes. @veggiesaurus is that okay?).

2021-03-23 08:08 UTC, YuHsuan-Hwang commented
Ok. Here I list some other params:
 - image/animation CompressionQuality: [1, 32]
 - contourSmoothingFactor: [1, 33]
 - contourNumLevels: [1, 20]

2021-03-23 08:34 UTC, kswang1029 commented
> Ok. Here I list some other params:
> 
> * image/animation CompressionQuality: [1, 32]
> * contourSmoothingFactor: [1, 33]
> * contourNumLevels: [1, 20]

Maybe I should get these value validation rules implemented. Will do so.

2021-03-23 10:18 UTC, kswang1029 commented
@YuHsuan-Hwang I have modified the value validators according to your findings. I manually set the upper bound for alpha to 1000000 as a sensible one.

2021-03-26 10:01 UTC, veggiesaurus approved these changes

2021-03-26 10:57 UTC, confluence commented on schemas/preference_schema_1.json
> +            "description": "should be 'streamImageTilesWhileZooming'???\n\nADJUST WITH CAUTION. A boolean flag to enable/disable image tile stream for intermediate zoom levels when image zooming is i
This looks like an outstanding query about the preference name. Should we rename this preference in the code?

2021-03-28 07:34 UTC, kswang1029 commented on schemas/preference_schema_1.json
> +            "description": "should be 'streamImageTilesWhileZooming'???\n\nADJUST WITH CAUTION. A boolean flag to enable/disable image tile stream for intermediate zoom levels when image zooming is i
what it actually means is raster "image", not contour. So I think we better rename it to be consistent.

2021-03-29 14:43 UTC, veggiesaurus commented on schemas/preference_schema_1.json
> +            "description": "should be 'streamImageTilesWhileZooming'???\n\nADJUST WITH CAUTION. A boolean flag to enable/disable image tile stream for intermediate zoom levels when image zooming is i
yes, we should probably rename it

2021-04-03 05:58 UTC, kswang1029 commented
ok to merge this?

2021-04-03 06:13 UTC, YuHsuan-Hwang approved these changes

2021-04-03 09:45 UTC, acdo2002 approved these changes

2021-04-06 07:13 UTC, confluence requested changes

2021-04-06 07:13 UTC, confluence commented on schemas/preference_schema_1.json
> +            "description": "should be 'streamImageTilesWhileZooming'???\n\nADJUST WITH CAUTION. A boolean flag to enable/disable image tile stream for intermediate zoom levels when image zooming is i
This comment should be taken out before we merge. If the name needs to be changed, an issue should be made for it.

2021-04-06 07:28 UTC, kswang1029 commented on schemas/preference_schema_1.json
> +            "description": "should be 'streamImageTilesWhileZooming'???\n\nADJUST WITH CAUTION. A boolean flag to enable/disable image tile stream for intermediate zoom levels when image zooming is i
removed via 7280b64

2021-04-06 08:03 UTC, confluence approved these changes

2021-04-06 08:29 UTC, merged